baseurl = "/"
googleAnalytics = "UA-XXXXXXX-Y"
languageCode = "en-us"
theme = "phugo"
title = "Marie's Travelogue"
[params]
author = "julian cowell"
description = "Marie's Travelogue"
keywords = "photogallery, photoblog, beakyspil, mariecowell"
[params.footer.contact]
buttontext = "Send"
headline = "Get in touch"
realemail = "mariecowell@gmail.com"
resettext = "Reset"
[params.footer.contact.email]
text = "Email *"
warning = "Please, enter your email."
[params.footer.contact.message]
text = "Message *"
warning = "Please, enter your message"
[params.footer.contact.name]
text = "Name *"
warning = "Please, enter your name"
[params.footer.copyright]
name = "Julian Cowell"
[params.footer.paragraph]
headline = "Marie's Trip To Japan"
text = "A fun and informative two weeks in April 2017. I spent a week in Tokyo, and then flew to Shanghai for another 6 days."
[params.footer.social]
headline = "Follow me"
[[params.footer.social.links]]
icon = "fa-twitter"
label = "Twitter"
url = "#"
[[params.footer.social.links]]
icon = "fa-facebook"
label = "Facebook"
url = "#"
[[params.footer.social.links]]
icon = "fa-instagram"
label = "Instagram"
url = "#"
[[params.header.links]]
icon = "fa-info-circle"
name = "About"
url = "#footer"
